module.exports = {
  docs: [
    {
      type: 'category',
      label: 'V1.Architecture, Design and Threat Modeling',
      items: [
        'V1.1.1-Secure-Software-Development-Lifecycle',
        'V1.1.2-Secure-Software-Development-Lifecycle',
        'V1.1.3-Secure-Software-Development-Lifecycle',
        'V1.1.4-Secure-Software-Development-Lifecycle',
        'V1.1.5-Secure-Software-Development-Lifecycle',
        'V1.1.6-Secure-Software-Development-Lifecycle',
        'V1.1.7-Secure-Software-Development-Lifecycle',
        'V1.2.1-Authentication-Architecture',
        'V1.2.2-Authentication-Architecture',
        'V1.2.3-Authentication-Architecture',
        'V1.2.4-Authentication-Architecture',
        'V1.4.1-Access-Control-Architecture',
        'V1.4.4-Access-Control-Architecture',
        'V1.4.5-Access-Control-Architecture',
        'V1.5.1-Input-and-Output-Architecture',
        'V1.5.2-Input-and-Output-Architecture',
        'V1.5.3-Input-and-Output-Architecture',
        'V1.5.4-Input-and-Output-Architecture',
        'V1.6.1-Cryptographic-Architecture',
        'V1.6.2-Cryptographic-Architecture',
        'V1.6.3-Cryptographic-Architecture',
        'V1.6.4-Cryptographic-Architecture',
        'V1.7.1-Errors,-Logging-and-Auditing-Architecture',
        'V1.7.2-Errors,-Logging-and-Auditing-Architecture',
        'V1.8.1-Data-Protection-and-Privacy-Architecture',
        'V1.8.2-Data-Protection-and-Privacy-Architecture',
        'V1.9.1-Communications-Architecture',
        'V1.9.2-Communications-Architecture',
        'V1.10.1-Malicious-Software-Architecture',
        'V1.11.1-Business-Logic-Architecture',
        'V1.11.2-Business-Logic-Architecture',
        'V1.11.3-Business-Logic-Architecture',
        'V1.12.2-Secure-File-Upload-Architecture',
        'V1.14.1-Configuration-Architecture',
        'V1.14.2-Configuration-Architecture',
        'V1.14.3-Configuration-Architecture',
        'V1.14.4-Configuration-Architecture',
        'V1.14.5-Configuration-Architecture',
        'V1.14.6-Configuration-Architecture',
      ],
    },
{
      type: 'category',
      label: 'V2.Authentication',
      items: [
        'V2.1.1-Password-Security',
        'V2.1.2-Password-Security',
        'V2.1.3-Password-Security',
        'V2.1.4-Password-Security',
        'V2.1.5-Password-Security',
        'V2.1.6-Password-Security',
        'V2.1.7-Password-Security',
        'V2.1.8-Password-Security',
        'V2.1.9-Password-Security',
        'V2.1.10-Password-Security',
        'V2.1.12-Password-Security',
        'V2.2.1-General-Authenticator-Security',
        'V2.2.2-General-Authenticator-Security',
        'V2.2.3-General-Authenticator-Security',
        'V2.2.4-General-Authenticator-Security',
        'V2.2.5-General-Authenticator-Security',
        'V2.2.6-General-Authenticator-Security',
        'V2.2.7-General-Authenticator-Security',
        'V2.3.1-Authenticator-Lifecycle',
        'V2.3.2-Authenticator-Lifecycle',
        'V2.3.3-Authenticator-Lifecycle',
        'V2.4.1-Credential-Storage',
        'V2.4.2-Credential-Storage',
        'V2.4.3-Credential-Storage',
        'V2.4.4-Credential-Storage',
        'V2.4.5-Credential-Storage',
        'V2.5.1-Credential-Recovery',
        'V2.5.3-Credential-Recovery',
        'V2.5.5-Credential-Recovery',
        'V2.5.6-Credential-Recovery',
        'V2.5.7-Credential-Recovery',
        'V2.6.1-Look-up-Secret-Verifier',
        'V2.6.2-Look-up-Secret-Verifier',
        'V2.6.3-Look-up-Secret-Verifier',
        'V2.7.2-Out-of-Band-Verifier',
        'V2.7.3-Out-of-Band-Verifier',
        'V2.7.4-Out-of-Band-Verifier',
        'V2.7.5-Out-of-Band-Verifier',
        'V2.7.6-Out-of-Band-Verifier',
        'V2.8.1-One-Time-Verifier',
        'V2.8.2-One-Time-Verifier',
        'V2.8.3-One-Time-Verifier',
        'V2.8.4-One-Time-Verifier',
        'V2.8.5-One-Time-Verifier',
        'V2.8.6-One-Time-Verifier',
        'V2.8.7-One-Time-Verifier',
        'V2.9.1-Cryptographic-Verifier',
        'V2.9.2-Cryptographic-Verifier',
        'V2.9.3-Cryptographic-Verifier',
        'V2.10.1-Service-Authentication',
        'V2.10.2-Service-Authentication',
        'V2.10.3-Service-Authentication',
        'V2.10.4-Service-Authentication',
      ],
    },
{
      type: 'category',
      label: 'V3.Session Management',
      items: [
        'V3.1.1-Fundamental-Session-Management-Security',
        'V3.2.1-Session-Binding',
        'V3.2.2-Session-Binding',
        'V3.2.3-Session-Binding',
        'V3.2.4-Session-Binding',
        'V3.3.1-Session-Termination',
        'V3.3.2-Session-Termination',
        'V3.3.3-Session-Termination',
        'V3.3.4-Session-Termination',
        'V3.4.1-Cookie-based-Session-Management',
        'V3.4.2-Cookie-based-Session-Management',
        'V3.4.3-Cookie-based-Session-Management',
        'V3.4.4-Cookie-based-Session-Management',
        'V3.4.5-Cookie-based-Session-Management',
        'V3.5.1-Token-based-Session-Management',
        'V3.5.2-Token-based-Session-Management',
        'V3.5.3-Token-based-Session-Management',
        'V3.6.1-Federated-Re-authentication',
        'V3.6.2-Federated-Re-authentication',
        'V3.7.1-Defenses-Against-Session-Management-Exploits', 
      ],
    },
{
      type: 'category',
      label: 'V4.Access Control',
      items: [
        'V4.1.1-General-Access-Control-Design',
        'V4.1.2-General-Access-Control-Design',
        'V4.1.3-General-Access-Control-Design',
        'V4.1.5-General-Access-Control-Design',
        'V4.2.1-Operation-Level-Access-Control',
        'V4.2.2-Operation-Level-Access-Control',
        'V4.3.1-Other-Access-Control-Considerations',
        'V4.3.2-Other-Access-Control-Considerations',
        'V4.3.3-Other-Access-Control-Considerations',
      ],
    },
{
      type: 'category',
      label: 'V5.Validation, Sanitization and Encoding',
      items: [
        'V5.1.1-Input-Validation',
        'V5.1.2-Input-Validation',
        'V5.1.3-Input-Validation',
        'V5.1.4-Input-Validation',
        'V5.1.5-Input-Validation',
        'V5.2.1-Sanitization-and-Sandboxing',
        'V5.2.2-Sanitization-and-Sandboxing',
        'V5.2.3-Sanitization-and-Sandboxing',
        'V5.2.4-Sanitization-and-Sandboxing',
        'V5.2.5-Sanitization-and-Sandboxing',
        'V5.2.6-Sanitization-and-Sandboxing',
        'V5.2.7-Sanitization-and-Sandboxing',
        'V5.2.8-Sanitization-and-Sandboxing',
        'V5.3.1-Output-Encoding-and-Injection-Prevention',
        'V5.3.2-Output-Encoding-and-Injection-Prevention',
        'V5.3.3-Output-Encoding-and-Injection-Prevention',
        'V5.3.4-Output-Encoding-and-Injection-Prevention',
        'V5.3.5-Output-Encoding-and-Injection-Prevention',
        'V5.3.6-Output-Encoding-and-Injection-Prevention',
        'V5.3.7-Output-Encoding-and-Injection-Prevention',
        'V5.3.8-Output-Encoding-and-Injection-Prevention',
        'V5.3.9-Output-Encoding-and-Injection-Prevention',
        'V5.3.10-Output-Encoding-and-Injection-Prevention',
        'V5.4.1-Memory,-String,-and-Unmanaged-Code',
        'V5.4.2-Memory,-String,-and-Unmanaged-Code',
        'V5.4.3-Memory,-String,-and-Unmanaged-Code',
        'V5.5.1-Deserialization-Prevention',
        'V5.5.2-Deserialization-Prevention',
        'V5.5.3-Deserialization-Prevention',
        'V5.5.4-Deserialization-Prevention',
      ],
    },
{
      type: 'category',
      label: 'V6.Stored Cryptography',
      items: [
        'V6.1.1-Data-Classification',
        'V6.1.2-Data-Classification',
        'V6.1.3-Data-Classification',
        'V6.2.1-Algorithms',
        'V6.2.2-Algorithms',
        'V6.2.3-Algorithms',
        'V6.2.4-Algorithms',
        'V6.2.5-Algorithms',
        'V6.2.6-Algorithms',
        'V6.2.7-Algorithms',
        'V6.2.8-Algorithms',
        'V6.3.1-Random-Values',
        'V6.3.2-Random-Values',
        'V6.3.3-Random-Values',
        'V6.4.1-Secret-Management',
        'V6.4.2-Secret-Management',
      ],
    },
{
      type: 'category',
      label: 'V7.Error Handling and Logging',
      items: [
        'V7.1.1-Log-Content',
        'V7.1.2-Log-Content',
        'V7.1.3-Log-Content',
        'V7.1.4-Log-Content',
        'V7.2.1-Log-Processing',
        'V7.2.2-Log-Processing',
        'V7.3.1-Log-Protection',
        'V7.3.3-Log-Protection',
        'V7.3.4-Log-Protection',
        'V7.4.1-Error-Handling',
        'V7.4.2-Error-Handling',
        'V7.4.3-Error-Handling',
      ],
    },
{
      type: 'category',
      label: 'V8:Data Protection',
      items: [
        'V8.1.1-General-Data-Protection',
        'V8.1.2-General-Data-Protection',
        'V8.1.3-General-Data-Protection',
        'V8.1.4-General-Data-Protection',
        'V8.1.5-General-Data-Protection',
        'V8.1.6-General-Data-Protection',
        'V8.2.1-Client-side-Data-Protection',
        'V8.2.2-Client-side-Data-Protection',
        'V8.2.3-Client-side-Data-Protection',
        'V8.3.1-Sensitive-Private-Data',
        'V8.3.2-Sensitive-Private-Data',
        'V8.3.3-Sensitive-Private-Data',
        'V8.3.4-Sensitive-Private-Data',
        'V8.3.5-Sensitive-Private-Data',
        'V8.3.6-Sensitive-Private-Data',
        'V8.3.7-Sensitive-Private-Data',
        'V8.3.8-Sensitive-Private-Data',
      ],
    },
{
      type: 'category',
      label: 'V9:Communication',
      items: [
        'V9.1.1-Client-Communication-Security',
        'V9.1.2-Client-Communication-Security',
        'V9.1.3-Client-Communication-Security',
        'V9.2.1-Server-Communication-Security',
        'V9.2.2-Server-Communication-Security',
        'V9.2.3-Server-Communication-Security',
        'V9.2.4-Server-Communication-Security',
        'V9.2.5-Server-Communication-Security',
      ],
    },
{
      type: 'category',
      label: 'V10:Malicious Code',
      items: [
        'V10.1.1-Code-Integrity',
        'V10.2.1-Malicious-Code-Search',
        'V10.2.2-Malicious-Code-Search',
        'V10.2.3-Malicious-Code-Search',
        'V10.2.4-Malicious-Code-Search',
        'V10.2.6-Malicious-Code-Search',
        'V10.3.1-Application-Integrity',
        'V10.3.2-Application-Integrity',
        'V10.3.3-Application-Integrity',
      ],
    },
{
      type: 'category',
      label: 'V11:Business Logic',
      items: [
        'V11.1.1-Business-Logic-Security',
        'V11.1.2-Business-Logic-Security',
        'V11.1.3-Business-Logic-Security',
        'V11.1.4-Business-Logic-Security',
        'V11.1.5-Business-Logic-Security',
        'V11.1.6-Business-Logic-Security',
        'V11.1.7-Business-Logic-Security',
        'V11.1.8-Business-Logic-Security',
      ],
    },
{
      type: 'category',
      label: 'V12:Files and Resources',
      items: [
        'V12.1.1-File-Upload',
        'V12.1.2-File-Upload',
        'V12.1.3-File-Upload',
        'V12.2.1-File-Integrity',
        'V12.3.1-File-Execution',
        'V12.3.2-File-Execution',
        'V12.3.3-File-Execution',
        'V12.3.4-File-Execution',
        'V12.3.5-File-Execution',
        'V12.3.6-File-Execution',
        'V12.4.1-File-Storage',
        'V12.4.2-File-Storage',
        'V12.5.1-File-Download',
        'V12.5.2-File-Download',
        'V12.6.1-SSRF-Protection'
      ],
    },
{
      type: 'category',
      label: 'V13:API and Web Service',
      items: [
        'V13.1.1-Generic-Web-Service-Security',
        'V13.1.3-Generic-Web-Service-Security',
        'V13.1.4-Generic-Web-Service-Security',
        'V13.1.5-Generic-Web-Service-Security',
        'V13.2.1-RESTful-Web-Service',
        'V13.2.2-RESTful-Web-Service',
        'V13.2.3-RESTful-Web-Service',
        'V13.2.5-RESTful-Web-Service',
        'V13.2.6-RESTful-Web-Service',
        'V13.3.1-SOAP-Web-Service',
        'V13.3.2-SOAP-Web-Service',
        'V13.4.1-GraphQL',
        'V13.4.2-GraphQL',
      ],
    },
{
      type: 'category',
      label: 'V14:Configuration',
      items: [
        'V14.4.3-HTTP-Security-Headers',
        'V14.4.7-HTTP-Security-Headers',
        'getting-started',
        'create-a-page',
        'create-a-document',
        'create-a-blog-post',
        'markdown-features',
      ],
    },
  ],
};
