name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Triggers on all branches
    tags:
      - '*'  # Triggers on all tags

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:15.12-alpine3.13
    if: github.ref == 'refs/heads/main'  # Replace 'main' with your default branch if different
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd website && yarn install

      - name: Build project
        run: cd website && yarn build && mv ./build ../build && ls ../build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
