name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Triggers on all branches
    tags:
      - '*'  # Triggers on all tags

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:15.12-alpine3.13
    if: github.ref != 'refs/heads/main'  # Replace 'main' with your default branch if different
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to website directory
        run: cd website

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    container: node:15.12-alpine3.13
    if: github.ref == 'refs/heads/main'  # Replace 'main' with your default branch if different
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to website directory
        run: cd website

      - name: Install dependencies
        run: cd website && yarn install

      - name: Build project
        run: cd website && yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: website/build
